### PR TITLE
feat(xychart): support onPointerDown event

### PR DESCRIPTION
**Pull request by abusada**
Fixes https://github.com/airbnb/visx/issues/1438
#### :boom: Breaking Changes

-

#### :rocket: Enhancements

-

#### :memo: Documentation

-

#### :bug: Bug Fix

-

#### :house: Internal

-

### CODE REVIEW

**Comment by abusada** [comment]
Hello, any plans to take a look at this?

**Comment by dwootton** [comment]
Would love to see this integrated if possible– would unblock a ton of advanced interaction design on charts without us having to leave the XYChart component @williaster.

**Review by williaster — APPROVED** [review]
sorry for the delayed review, haven't had a ton of bandwidth. code lgtm, need to figure out why CI isn't running.

**Comment by williaster** [comment]
@abusada can you rebase and force push this to see if it triggers CI?

**Comment by dwootton** [comment]
No worries! Appreciate the quick approval Chris– will unblock a bunch of fun interaction design to have access to more event types.

**Comment by abusada** [comment]
Sorry guys i also just saw this, i rebased and force pushed

**Comment by williaster** [comment]
looks great! will land momentarily (another build/release is in progress)

**Pull request merged**
