### PR TITLE
fix(demo): fix missing API documentation

### LINKED ISSUE #1647: visx/shape documentation missing
See [https://airbnb.io/visx/docs/shape](https://airbnb.io/visx/docs/shape), and scroll down. 

I'm not crazy right, there's supposed to be more content below the examples?

Screen Shot 2023-02-03 at 10 32 07 PM

### PR DESCRIPTION
**Pull request by jonambas**
#### :memo: Documentation

- Fixes missing `@visx/shape` `@visx/glyph` `@visx/gradient` `@visx/xychart` documentation
- Fixes `@visx/point` readme 
- Closes #1647

### CODE REVIEW

**Comment by williaster** [comment]
Hey @jonambas thanks so much for this fix! 🙏 

Several other packages actually have the same issue right now, would you be interested in taking a shot at updating all of them? I think anything that's not importing from a `<package>/src/*` folder will have this issue, for example:
- `@visx/axis` docs [**are** working](https://airbnb.io/visx/docs/axis) and they use the [`src/*` import](https://github.com/airbnb/visx/blob/master/packages/visx-demo/src/pages/docs/axis.tsx#L3)
- `@visx/xychart` docs [**are not** working](https://airbnb.io/visx/docs/axis) and they use the [non`-src/` import](https://github.com/airbnb/visx/blob/master/packages/visx-demo/src/pages/docs/xychart.tsx#L3)

**Comment by jonambas** [comment]
Sure thing! Will try take a look sometime this week

**Comment by jonambas** [comment]
@williaster Checked other pages, think I caught all of them. 

Also fixed this small visual bug with the `visx-point` readme:

Screen Shot 2023-02-11 at 9 05 59 AM

After:

Screen Shot 2023-02-11 at 9 10 38 AM

**Review by williaster — APPROVED** [review]
@jonambas amazing, thanks so much for taking a pass at the other package docs 🙏 

LGTM, will land once CI passes.

**Pull request merged**
