### PR TITLE
feat(sankey): add @visx/sankey

### PR DESCRIPTION
**Pull request by jacksonhardaker**
#### :rocket: Enhancements

- Adds support for sankey layouts via `d3-sankey`
- Per suggestion to add in https://github.com/airbnb/visx/issues/190

### CODE REVIEW

**Comment by jacksonhardaker** [comment]
@williaster When you have a moment to approve the workflow again, I believe I've resolved the steps (at least locally) so that it will complete. That said, I'm not sure what the happo output will be, given there are new additions to the demo site.

**Comment by jacksonhardaker** [comment]
@williaster Happy to help resolve any issues surfaced in happo, if you can point me to them? I suspect most of the issues are because of the newly added examples/docs?

**Review by williaster — APPROVED** [review]
Hey @jacksonhardaker thank you SO MUCH for this awesome contribution. everything looks spectacular, we appreciate how well you followed code styles/all of the integration points for a new package including tests and a gallery example with sandbox 🙏 🙏 🙏 

major apologies on the slow review, it's been a really busy time for the maintainers. I had 2x _**super**_ small comments and then I think it's good to go!! 🚀  THANK YOU AGAIN! it's always exciting to have new packages and functionality.

**Comment by jacksonhardaker** [comment]
Thanks @williaster. I made those small tweaks, so should be good to go.

**Comment by williaster** [comment]
amazing! lgtm, will merge this and it should be released/live soon!

thanks again for the great work here 🙌

**Pull request merged**
