### PR TITLE
feat(brush): disable drag overlay

### PR DESCRIPTION
**Pull request by Onxi95**
Hi! Thank you for this wonderful library - without you I would probably cry in the corner thinking how to implement fancy charts :sweat_smile: 

#### :rocket: Enhancements

- added `disableDraggingOverlay` to `Brush` in order to be able to use `Brush` only as a scroll (without possibility of changing its size)

#### :thinking: Motivation

I was building something similar to bar chart. The requirements changed a bit (ofc :sweat_smile:) and the chart has to have multiple columns with minimum width and scrollbar if needed. The closest solution to achieve this result is `Brush` (It doesn't handle scroll events, but manual scroll using mouse is good enough for our use-case).
I styled the brush to look like a standard, gray scrollbar, but when I click outside of it, new area of brush is created. There's `disableDraggingSelection` prop, but it affects scrollbar, and there's no option to do something similar but to overlay. I managed to work around it by using `pointer-events: none`, but I think it's a bit hacky solution and making it available in the lib might be beneficial :D 

#### :test_tube: How to test it?

in brush example (`packages/visx-demo/src/sandboxes/visx-brush/Example.tsx`), adjust `<Brush />` component like:

```TSX
          <Brush
            xScale={brushDateScale}
            yScale={brushStockScale}
            disableDraggingOverlay // <- new prop
            width={xBrushMax}
            height={yBrushMax}
            margin={brushMargin}
            // handleSize={8}
            innerRef={brushRef}
            // resizeTriggerAreas={['left', 'right']}
            brushDirection="horizontal"
            initialBrushPosition={initialBrushPosition}
            onChange={onBrushChange}
            // onClick={() => setFilteredStock(stock)}
            selectedBoxStyle={selectedBrushStyle}
            useWindowMoveEvents
            // renderBrushHandle={(props) => <BrushHandle {...props} />}
          />
```

https://github.com/Onxi95/visx/assets/48386403/1011b729-2e55-4051-bf2a-b52ab255fc7c

### CODE REVIEW

**Comment by Onxi95** [comment]
Hi @williaster :wave: Can you take a look at it in your free time? :smile:

**Comment by williaster** [comment]
Hi @Onxi95 👋  thanks for the ping, sorry this slipped through. It looks like CI hasn't run for the PR, can you try to rebase just to re-trigger things? I'll try to take a look at it ASAP, it may be next week due to the holiday this week

**Comment by Onxi95** [comment]
Hello @williaster :wave: 

I was looking around, trying to see what's going on with actions, but at the end I saw that 

`1 workflow awaiting approval`
image


I guess it's needed to trigger actions and I think I don't have permissions to do it :sweat_smile: 

Launched the jobs from `pull_request.yml` (skipped `yarn run happo-ci-github-actions`)  locally and I didn't see any issues - if I miss something, please let me know :pray:

**Review by williaster — APPROVED** [review]
Thanks for your patience here @Onxi95 🙏  this lgtm, thank you for the contribution!

**Pull request merged**
